<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net6.0-windows;net7.0-windows;net8.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <NoWarn>CS1587</NoWarn>
    <DebugType>embedded</DebugType>
    <EnablePackageValidation>true</EnablePackageValidation>
    <Title>$(AssemblyName)</Title>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>SafeTwice S.L.</Authors>
    <PackageProjectUrl>https://github.com/SafeTwice/Utilities.DotNet.WPF</PackageProjectUrl>
    <RepositoryUrl>https://github.com/SafeTwice/Utilities.DotNet.WPF.git</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageTags>.net;dotnet;utilities;util;wpf</PackageTags>
    <Company>www.safetwice.com</Company>
    <Description>WPF utilities library for .NET</Description>
    <Copyright>Copyright © 2022-2025 SafeTwice S.L.</Copyright>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
    <RootNamespace>Utilities.DotNet.WPF</RootNamespace>
    <Version>1.3-rc3</Version>
    <AssemblyVersion>1.2.1.102</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Utilities.DotNet" Version="1.5-rc1" />
    <PackageReference Include="Utilities.DotNet.Collections" Version="1.5-rc1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <PropertyGroup Condition="'$(GITHUB_EVENT_NAME)'=='release'">
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
