<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net6.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>10</LangVersion>
        <UseWPF>true</UseWPF>
        <RootNamespace>Utilities.DotNet.WPF.Demo</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Lib\Utilities.DotNet.WPF.csproj" />
    </ItemGroup>

</Project>
